const ActionTypes = {
  FETCH_BOOKS_REQUEST: `FETCH_BOOKS_REQUEST`,
  FETCH_BOOKS_SUCCESS: `FETCH_BOOKS_SUCCESS`,
  FETCH_BOOKS_FAILURE: `FETCH_BOOKS_FAILURE`,
  BOOK_ADDED_TO_CART: `BOOK_ADDED_TO_CART`,
  BOOK_REMOVE_FROM_CART: `BOOK_REMOVE_FROM_CART`,
  ALL_BOOKS_REMOVE_FROM_CART: `ALL_BOOKS_REMOVE_FROM_CART`,
};

export default ActionTypes;
